---
- hosts: "masters, workers"
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: Disable Firewall
       command: ufw disable

     - name: Turn off swap
       command: swapoff -a

     - name: Remove swap entry from /etc/fstab
       command: sed -i '/swap/d' /etc/fstab

     - name: Create containerd config file
       file:
         path: "/etc/modules-load.d/containerd.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/modules-load.d/containerd.conf"
         block: |
               overlay
               br_netfilter

     - name: modprobe
       shell: |
               sudo modprobe overlay
               sudo modprobe br_netfilter

     - name: Set system configurations for Kubernetes networking
       file:
         path: "/etc/sysctl.d/99-kubernetes-cri.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/sysctl.d/99-kubernetes-cri.conf"
         block: |
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                net.bridge.bridge-nf-call-ip6tables = 1

     - name: Apply new settings
       command: sudo sysctl --system

     - name: Add Docker GPG Key
       shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
 
     - name: Add Kubernetes GPG Key
       shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
 
     - name: Add Docker Repository
       shell: echo "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
 
     - name: Add Kubernetes Repository
       shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

     - name: Run apt update
       apt:
         update_cache: yes
       become: yes

     - name: Install Helm on Master Node
       shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sudo bash
       when: inventory_hostname in groups['masters']

     - name: Install kubeadm
       apt:
         name: kubeadm
         state: present
 
     - name: Install kubelet
       apt:
         name: kubelet
         state: present
 
     - name: Install kubectl
       apt:
         name: kubectl
         state: present
 
     - name: Install containerd.io
       apt:
         name: containerd.io
         state: present

     - name: Run containerd config default
       shell: containerd config default | tee /etc/containerd/config.toml
 
     - name: Modify SystemdCgroup setting in containerd configuration
       shell: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

     - name: Create /etc/crictl.yaml file
       shell: |
         cat <<EOF | sudo tee /etc/crictl.yaml
         runtime-endpoint: unix:///var/run/containerd/containerd.sock
         image-endpoint: unix:///var/run/containerd/containerd.sock
         timeout: 30
         debug: false
         EOF

     - name: Restart Containerd service
       systemd:
         name: containerd
         state: restarted

     - name: Check Containerd service status
       systemd:
         name: containerd
         state: started
       register: containerd_status
 
     - name: Ensure Containerd status is active
       fail:
         msg: "Containerd service is not in the 'active' state."
       when: containerd_status.changed

     - name: Add source commands to ~/.profile on master
       lineinfile:
         path: ~/.profile
         line: |
           source <(kubectl completion bash)
           source <(kubeadm completion bash)
           source <(crictl completion bash)
           source <(helm completion bash)
           alias k=kubectl
           complete -F __start_kubectl k
           export KUBE_EDITOR=nano
           export NOW="--force --grace-period 0"
       when: inventory_hostname in groups['masters']

     - name: Add source commands to ~/.profile on workers
       lineinfile:
         path: ~/.profile
         line: |
           source <(kubectl completion bash)
           source <(kubeadm completion bash)
           source <(crictl completion bash)
           alias k=kubectl
           complete -F __start_kubectl k
           export KUBE_EDITOR=nano
           export NOW="--force --grace-period 0"
       when: inventory_hostname in groups['workers']

     - name: Source the updated ~/.profile
       shell: source ~/.profile
       args:
         executable: /bin/bash
